# specify the node version
FROM node:8

# Specify path to the directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.*.json ./

# run npm install to install the required dependencies
RUN npm install

# bundle the source code inside the docker container
COPY . .

# specify the port

EXPOSE 8080

# command to run application using command line interface
CMD ["npm", "start"]


